name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      - name: Build client
        working-directory: ./frontend
        run: |
          # Add build commands if required
          # Example: npm run build

      - name: Build Docker image
        run: |
          docker build -t hoho25a5haha/my-app:latest .
        

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push hoho25a5haha/my-app:latest

      - name: Deploy Docker container
        run: docker run -d -p 3000:3000 hoho25a5haha/my-app:latest
